apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: proxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
